app/views/components/autocompleteList.scala.html, app/views/components/errorSummary.scala.html, app/views/components/summaryYesNo.scala.html, app/views/components/yesNoRadio.scala.html, app/views/purchased_products/remove.scala.html, app/views/travel_details/arriving_ni.scala.html, app/views/travel_details/eu_evidence_item.scala.html, app/views/travel_details/ucc_relief_item.scala.html, app/views/travel_details/ukexcise_paid.scala.html, app/views/travel_details/ukexcise_paid_item.scala.html, app/views/travel_details/ukvat_paid_item.scala.html, conf/messages.cy, test/controllers/EUEvidenceControllerSpec.scala, test/controllers/UKExcisePaidControllerSpec.scala, test/controllers/UKVatPaidControllerSpec.scala, test/controllers/UccReliefControllerSpec.scala
- Radio Buttons Play UI 1
- https://github.com/hmrc/bc-passengers-acceptance-tests/pull/269
=> PAS-1425: Radio Buttons Play UI 1

app/views/amendments/pending_payment.scala.html, app/views/travel_details/confirm_age.scala.html, app/views/travel_details/goods_bought_inside_and_outside_eu.scala.html, app/views/travel_details/goods_bought_outside_eu.scala.html, app/views/travel_details/private_travel.scala.html, app/views/travel_details/uk_resident.scala.html, test/controllers/PendingPaymentControllerSpec.scala, test/controllers/TravelDetailsControllerSpec.scala, test/controllers/UKResidentControllerSpec.scala
- Play UI Radio Buttons 2
- AT PR link: https://github.com/hmrc/bc-passengers-acceptance-tests/pull/270
=> PAS-933: Play UI Radio Buttons 2

app/views/alcohol/alcohol_input.scala.html, app/views/amendments/declaration_retrieval.scala.html, app/views/amendments/previous_declaration.scala.html, app/views/components/autocompleteList.scala.html, app/views/components/govukTimeInput.scala.html, app/views/components/inputDate.scala.html, app/views/components/inputRadioH2.scala.html, app/views/components/inputText.scala.html, app/views/components/inputTime.scala.html, app/views/components/linkAsButton.scala.html, app/views/components/package.scala, app/views/declaration/enter_your_details.scala.html, app/views/other_goods/other_goods_input.scala.html, app/views/tobacco/tobacco_input.scala.html, app/views/travel_details/arriving_ni.scala.html, app/views/travel_details/eu_country_check.scala.html, app/views/viewmodels/TimeInput.scala, conf/messages, conf/messages.cy, test/controllers/ArrivingNIControllerSpec.scala, test/controllers/CalculateDeclareControllerSpec.scala, test/controllers/DeclarationRetrievalControllerSpec.scala, test/controllers/PreviousDeclarationControllerSpec.scala, test/controllers/TravelDetailsControllerSpec.scala
AT : https://github.com/hmrc/bc-passengers-acceptance-tests/pull/271
=> PAS-1018 Play UI upgrade for User Information Page

app/views/alcohol/alcohol_input.scala.html, app/views/amendments/declaration_not_found.scala.html, app/views/components/display_item.scala.html, app/views/components/display_tax_breakdown.scala.html, app/views/components/warning.scala.html, app/views/declaration/declare_your_goods.scala.html, app/views/declaration/zero_to_declare_your_goods.scala.html, app/views/other_goods/other_goods_input.scala.html, app/views/purchased_products/dashboard.scala.html, app/views/purchased_products/done.scala.html, app/views/purchased_products/limit_exceed.scala.html, app/views/purchased_products/nothing_to_declare.scala.html, app/views/purchased_products/over_ninety_seven_thousand_pounds.scala.html, app/views/purchased_products/zero_to_declare.scala.html, app/views/tobacco/tobacco_input.scala.html, test/controllers/CalculateDeclareControllerSpec.scala, test/controllers/DashboardControllerSpec.scala, test/controllers/LimitExceedControllerSpec.scala
Play UI upgrade for Tables,H1,Links
AT PR link: https://github.com/hmrc/bc-passengers-acceptance-tests/pull/273
=> PAS-1171 Play UI upgrade for Tables,H1,Links

app/views/travel_details/ukexcise_paid_item.scala.html
External link not open in new tab
=> PAS-1425: External link not open in new tab

app/views/purchased_products/done.scala.html, app/views/purchased_products/nothing_to_declare.scala.html, app/views/purchased_products/over_ninety_seven_thousand_pounds.scala.html, app/views/purchased_products/zero_to_declare.scala.html, app/views/tobacco/no_of_sticks_weight_or_volume_input.scala.html
=> PAS-1171: Fixed content issue

it/repositories/BCPassengersSessionRepositoryISpec.scala
PAS-1422 
Bug fix - Fixing integration fix
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
=> PAS-1422 : Integration fix

app/views/declaration/declare_your_goods.scala.html, app/views/declaration/zero_to_declare_your_goods.scala.html
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
=> DDCE-2649: Invalid paragraph tag removed

app/views/components/inputInsetText.scala.html, app/views/declaration/enter_your_details.scala.html, check.sh, test/controllers/CalculateDeclareControllerSpec.scala
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
=> DDCE-2651:Fix conditionally revealing content

app/views/components/h1Product.scala.html, app/views/purchased_products/select_products.scala.html, app/views/travel_details/ukexcise_paid.scala.html
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
=> DDCE-2650: Passengers - Fieldset does not contain a legend (A)

app/views/components/inputCheckboxes.scala.html, app/views/components/otherGoodsInputRadio.scala.html, app/views/purchased_products/select_products.scala.html, build.sbt, conf/application.conf, project/AppDependencies.scala
Fixed one of the issues in here
=> DDCE-3731 - Fix fieldset legend for checkbox groups

app/views/components/autocompleteList.scala.html, app/views/templates/GovukLayoutWrapper.scala.html, conf/application.conf, project/AppDependencies.scala, test/controllers/ArrivingNIControllerSpec.scala
- Created new filter
- Check filter is working on pages using CSP evaluator chrome extension and console.
- Ran AT
=> DDCE-3739: Improve CSP

app/views/components/display_tax_breakdown.scala.html, app/views/purchased_products/done.scala.html, app/views/purchased_products/nothing_to_declare.scala.html, app/views/purchased_products/over_ninety_seven_thousand_pounds.scala.html, app/views/purchased_products/zero_to_declare.scala.html
To fix https://github.com/hmrc/accessibility-audits-external/issues/2541
=> DDCE-4226 - Fix table headers and columns numeric format

app/views/declaration/enter_your_details.scala.html
Fix for https://github.com/hmrc/accessibility-audits-external/issues/2545
=> DDCE-4228 - Fix email input autocomplete

README.md, a11y/AccessibilityConstants.scala, a11y/FrontendAccessibilitySpec.scala, app/controllers/CalculateDeclareController.scala, app/views/declaration/enter_your_details.scala.html, app/views/declaration/zero_declaration.scala.html, app/views/purchased_products/nothing_to_declare.scala.html, app/views/purchased_products/over_ninety_seven_thousand_pounds.scala.html, app/views/purchased_products/zero_to_declare.scala.html, build.sbt, conf/application.conf, it/repositories/BCPassengersSessionRepositoryISpec.scala, project/AppDependencies.scala
Changes from https://github.com/hmrc/bc-passengers-frontend/pull/427 are included here as well
=> DDCE-4293 - Fix sbt-linter errors

app/views/components/govukTimeInput.scala.html, app/views/declaration/enter_your_details.scala.html
- Date month and year input cannot be fixed because https://hmrcdigital.slack.com/archives/CJMUM9AG3/p1686733774840349
=> DDCE-4305 - Fix a11y info level

app/models/JourneyData.scala, app/models/dto.scala
DDCE-6688: OSP - P2 AA: Reference number field not accommodating spaces
=> DDCE-6688: OSP - P2 AA: Reference number field not accommodating spaces

app/models/dto.scala, conf/messages, conf/messages.cy, test/models/DtoTest.scala, test/views/declaration/YourJourneyDetailsViewSpec.scala
DDCE-6668: OSP - P2 AA: Month field not accepting name input
=> DDCE-6668: OSP - P2 AA: Month field not accepting name input

app/models/dto.scala, app/views/amendments/declaration_retrieval.scala.html, app/views/components/fieldset.scala.html, app/views/components/inputDate.scala.html, app/views/components/inputText.scala.html, app/views/declaration/journey_details.scala.html, app/views/declaration/what_is_your_email.scala.html
Changes - 
- removed parent fieldset and added H1 to journey_details.scala.html
=> DDCE-6889 P1: Nested fieldsets #9578 

app/views/alcohol/alcohol_input.scala.html, app/views/components/h1Product.scala.html, project/AppDependencies.scala
changes - 
- removed br from alcohol_input.scala.html
- removed classes fromH1 and added them to legend in h1Product.scala.html
=> DDCE-6872 P2: <br> tags used for presentation #9567

app/views/other_goods/other_goods_input.scala.html
changes - 
added govuk styling to link
=> DDCE-6915 P1: Link missing focus styling #9429

app/views/components/linkAsButton.scala.html, project/AppDependencies.scala
changes - 
- added data-module="govuk-button" to linkAsButton.scala.html
=> DDCE-6913 P1: Link styled and given button role needs JavaScript polyfill to act like button

app/views/declaration/journey_details.scala.html, project/AppDependencies.scala
changes - 
- removed redundant aria attributes from journey_details.scala.html
=> DDCE-6893 P3: Redundant ARIA roles and attribute

app/controllers/AlcoholInputController.scala, app/controllers/OtherGoodsInputController.scala, app/controllers/TobaccoInputController.scala, project/AppDependencies.scala, test/controllers/AlcoholInputControllerSpec.scala, test/controllers/OtherGoodsInputControllerSpec.scala, test/controllers/TobaccoInputControllerSpec.scala
Changes
- Updated AlcoholInputController to stop binding default country and currency values when adding a new alcohol item.
-  Updated AlcoholInputControllerSpec to reflect new Add behaviour
-  Added new test
=> DDCE-6841 P1: Pre-populated list items
